//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K4nvas.Market.Proxies.Ventas.ServicioVentas
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ListaCategoria", Namespace = "http://schemas.datacontract.org/2004/07/K4nvas.Market.Model", ItemName = "Categoria")]
    public class ListaCategoria : System.Collections.Generic.List<K4nvas.Market.Proxies.Ventas.ServicioVentas.Categoria>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Categoria", Namespace = "http://schemas.datacontract.org/2004/07/K4nvas.Market.Model")]
    public partial class Categoria : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string DescripcionField;

        private string DescripcionCortaField;

        private bool FlagEstadoField;

        private int IdCategoriaField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCorta
        {
            get
            {
                return this.DescripcionCortaField;
            }
            set
            {
                this.DescripcionCortaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlagEstado
        {
            get
            {
                return this.FlagEstadoField;
            }
            set
            {
                this.FlagEstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria
        {
            get
            {
                return this.IdCategoriaField;
            }
            set
            {
                this.IdCategoriaField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "K4nvas.Market.Proxies.Ventas.ServicioVentas.IVentasService")]
    public interface IVentasService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IVentasService/ListarCategoriaProducto", ReplyAction = "http://tempuri.org/IVentasService/ListarCategoriaProductoResponse")]
        K4nvas.Market.Proxies.Ventas.ServicioVentas.ListaCategoria ListarCategoriaProducto();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IVentasService/ListarCategoriaProducto", ReplyAction = "http://tempuri.org/IVentasService/ListarCategoriaProductoResponse")]
        System.Threading.Tasks.Task<K4nvas.Market.Proxies.Ventas.ServicioVentas.ListaCategoria> ListarCategoriaProductoAsync();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVentasServiceChannel : K4nvas.Market.Proxies.Ventas.ServicioVentas.IVentasService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentasServiceClient : System.ServiceModel.ClientBase<K4nvas.Market.Proxies.Ventas.ServicioVentas.IVentasService>, K4nvas.Market.Proxies.Ventas.ServicioVentas.IVentasService
    {

        public VentasServiceClient()
        {
        }

        public VentasServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public VentasServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public VentasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public VentasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public K4nvas.Market.Proxies.Ventas.ServicioVentas.ListaCategoria ListarCategoriaProducto()
        {
            return base.Channel.ListarCategoriaProducto();
        }

        public System.Threading.Tasks.Task<K4nvas.Market.Proxies.Ventas.ServicioVentas.ListaCategoria> ListarCategoriaProductoAsync()
        {
            return base.Channel.ListarCategoriaProductoAsync();
        }
    }
}
